### ISSUE TITLE
In-range values shown in red on the chart

### ISSUE THREAD

**Issue by ktomy** [bigdigital/xDrip-miband#1]
Hi, I am not even sure if it is a bug or a feature (but looks like a bug). When vbalues are decreasing, starting from high range, getting to the normal range, for some time they are shown in red color on the chart. Please see ![this](https://user-images.githubusercontent.com/1446257/97865053-dfb4a080-1d09-11eb-8f2b-4b88f8821fd0.jpeg) photo.
I am using Ver 0.3.2.1 on MiBand 5. Let me know if you need more data.
Thank you.

P.S. could you please pot on your blog whethere there is a way to contact/chat with the development team, besides creating issues here?

**Comment by bigdigital** [comment]
Hi. The red line is a prediction line. It shows you the predicted bg values for the next 30 minutes.
