### ISSUE TITLE
Custom watchfaces fail to sync in 0.3.2.6

### ISSUE THREAD

**Issue by ghost** [bigdigital/xDrip-miband#3]
## Expected Behavior

Valid MiBand 5 custom watchface `my_watchface.bin` file syncs to device.

## Current Behavior

MiBand 5 appears to time out while receiving watchface update.
## Steps to Reproduce
I used the default watchface, which works, to ensure there is no simple compatibility issues with mine.
1. `bonito:/storage/emulated/0/xdrip $ cp watchface.bin my_watchface.bin`
2. Either force or wait for a new sync to occur
3. Watch fails to sync after 3 to 20 seconds

Viewing event logs, WatchFaceGenerator does not appear to have any issues handling the file, but MiBandService never reports that it has been successfully installed.

I understand it's an experimental feature, but I'd love the opportunity to have the option to change the face while still viewing glucose levels. Has any development been done towards fixing this bug, or is this not even a priority?

**Comment by pcastelo** [comment]
same issue here
